name: Build and push

on:
  push:
    branches:
      - main
    paths:
      - forest/**
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: cd forest; pnpm install

      - name: Build
        run: cd forest; pnpm run build

      - name: Compress
        uses: a7ul/tar-action@v1.2.0
        id: compress
        with:
          command: c
          cwd: forest
          files: ./dist
          outPath: dist.tar.gz

      - name: Create folder and Move
        run: |
          mkdir -p forest/dist_compressed
          mv dist.tar.gz forest/dist_compressed/dist.tar.gz

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: forest/dist_compressed # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message